### PR TITLE
fix: PS 5.1 compatibility regressions and VM dedup bug

### LINKED ISSUE #411: PS 5.1 compatibility regressions: test runner blocks 5.1, Explore-AzurePricing JSON broken, URI encoding diff
## Problem

PR #395 (fixes #392) added PowerShell 5.1 compatibility to the pricing scripts. A/B testing on Windows (pwsh 7.5.4 vs PowerShell 5.1.26100) reveals **5 unit test failures on PS 5.1** and one real functional bug in the Explore script's JSON output.

## A/B Test Results

| Runtime | Passed | Failed | Total |
|---------|--------|--------|-------|
| **pwsh 7.5.4** | 87 | **0** | 87 |
| **PowerShell 5.1** | 82 | **5** | 87 |

### 1. Test runner blocks PS 5.1 entirely

`tests/unit/Run-PesterTests.ps1` has `#Requires -Version 7.0` on line 1. This hard-stops execution on PS 5.1 with:

`
The script 'Run-PesterTests.ps1' cannot be run because it contained a
"#requires" statement for Windows PowerShell 7.0.
`

The test runner should either drop the version gate or provide a PS 5.1-compatible path, since the scripts themselves now claim PS 5.1 support.

### 2. `Explore-AzurePricing.ps1` JSON output broken on PS 5.1 (4 failures)

**Root cause:** `ConvertFrom-Json` behaves differently between PS versions when parsing JSON arrays.

- **PS 7**: `ConvertFrom-Json` unwraps a JSON array into individual objects
- **PS 5.1**: `ConvertFrom-Json` returns the array as a **single nested object**

The script's JSON output path (` | ConvertTo-Json -Depth 3`) produces valid JSON on both runtimes, but when a consumer parses it with `ConvertFrom-Json` on PS 5.1, they get a single wrapper object containing an inner array instead of the expected flat list.

**Repro:**

`powershell
# PS 7 — works correctly
  = @('[{"a":1},{"a":2}]' | ConvertFrom-Json)
 .Count  # → 2

# PS 5.1 — broken
  = @('[{"a":1},{"a":2}]' | ConvertFrom-Json)
 .Count  # → 1  (wrapped array)
 [0].GetType()  # → System.Object[] (inner array)
`

**Failing tests:**

| Test | Expected | Got |
|------|----------|-----|
| Should return only distinct combinations | 2 | 1 |
| Should cap output to Top value | 3 | 1 |
| Should include ServiceName in each result | `'Virtual Machines'` | `@('Virtual Machines', 'Virtual Machines')` |
| Should include expected properties | `ServiceName, ProductName...` | `Count, Length, Rank, SyncRoot...` |

**This is a real functional bug** — not just a test issue. Any agent or downstream consumer parsing Explore output on PS 5.1 will get corrupted structure.

### 3. URI encoding difference for apostrophes (1 failure)

**Root cause:** `[System.Uri]::EscapeDataString()` behaves differently on .NET Framework 4.x (PS 5.1) vs .NET 8 (PS 7).

- **PS 7** (.NET 8): `'` → `%27` → `serviceName%20eq%20%27Virtual%20Machines%27`
- **PS 5.1** (.NET 4.x): `'` stays as `'` → `serviceName%20eq%20'Virtual%20Machines'`

The test asserts ` -like '*%27Virtual*Machines%27*'` which only matches the PS 7 encoding. The Azure Retail Prices API accepts both forms, so this is not a functional bug, but the test is PS 7-specific.

**Failing test:**

| Test | Issue |
|------|-------|
| should encode the filter parameter | Asserts `%27` encoding that only PS 7 produces |

### Fix 1: Remove `#Requires -Version 7.0` from test runner

Lower the gate to `#Requires -Version 5.1` or remove it entirely. Pester 5.7.1 works on PS 5.1 (confirmed during testing — installed and ran successfully).

### Fix 2: Fix `Explore-AzurePricing.ps1` JSON array output

Use a PS 5.1-safe wrapper so the output is consistently parseable. Options:

- **Option A**: Write `ConvertTo-Json -Depth 3` with explicit array wrapper that works on both runtimes
- **Option B**: Use `Write-Output` with `-NoEnumerate` or manually ensure array output

### Fix 3: Update URI encoding test assertion

Relax the test to accept both encoded (`%27`) and literal (`'`) apostrophes, since both are valid and the API accepts both.

### Fix 4: Add missing error-handling tests

PR #395 review comments flagged that the generic catch block could swallow non-HTTP exceptions. The current tests only cover the `[System.Net.WebException]` catch path. Add tests for:

- HTTP error on PS 7 (`HttpResponseException`)
- Non-HTTP exception rethrow (verify `throw` path works)
- Duck-type `-or` vs `-and` check correctness

## Files Affected

- `tests/unit/Run-PesterTests.ps1` — version gate
- `skills/azure-cost-calculator/scripts/Explore-AzurePricing.ps1` — JSON output
- `skills/azure-cost-calculator/scripts/lib/Invoke-RetailPricesQuery.ps1` — URI encoding
- `tests/unit/powershell/lib/Invoke-RetailPricesQuery.Tests.ps1` — encoding assertion
- `tests/unit/powershell/Explore-AzurePricing.Tests.ps1` — array parsing
- `tests/unit/powershell/Get-AzurePricing.Tests.ps1` — missing error tests

## Related

- #392 — Original PS 5.1 compatibility issue
- #395 — PR that introduced these changes
- #405 — Unit test coverage issue

### PR DESCRIPTION
**Pull request by ahmadabdalla**
## Summary

Fixes PS 5.1 compatibility regressions and a critical pre-existing VM dedup bug. All changes are cross-platform safe — PS 7 on macOS/Linux is unaffected.

Closes #411

### Bug fix: VM dedup logic (`Get-AzurePricing.ps1`)
The dedup code added `$primary` directly to `$deduped`, but when multiple items share `isPrimaryMeterRegion=true`, `$primary` is an array. This corrupts downstream `unitOfMeasure` (becomes array instead of string), breaking `Get-MonthlyMultiplier`. Fixed by wrapping with `Select-Object -First 1`. **This affected both PS 7 and PS 5.1.**

### Test runner version gate (`Run-PesterTests.ps1`)
`#Requires -Version 7.0` → `#Requires -Version 5.1`. Pester 5.7.1 works on PS 5.1; the gate was unnecessarily blocking execution.

### Explore test `ConvertFrom-Json` unwrap (`Explore-AzurePricing.Tests.ps1`)
PS 5.1's `ConvertFrom-Json` returns a JSON array as a single nested object instead of unwrapping it. Added `| ForEach-Object { $_ }` after `ConvertFrom-Json` at 5 call sites to force consistent array unwrap on both runtimes. The script output itself is correct — this was a test-consumer issue only.

### URI encoding test relaxation (`Invoke-RetailPricesQuery.Tests.ps1`)
PS 5.1 (.NET 4.x) `EscapeDataString` keeps `'` as-is; PS 7 (.NET 8) encodes to `%27`. Both are valid — the Azure API accepts either. Relaxed the assertion to accept both forms.

### New error-handling tests (`Get-AzurePricing.Tests.ps1`, `Explore-AzurePricing.Tests.ps1`)
Added tests for both scripts covering:
- HTTP error with `Response` property (duck-type catch path for PS 7 `HttpResponseException`)
- Non-HTTP exception rethrow (verifies generic catch re-throws unexpected errors)

### Unit tests — before vs after

| Runtime | Before | After |
|---------|--------|-------|
| **PS 7** (pwsh 7.5.4) | 91 pass, 0 fail | **97 pass, 0 fail** |
| **PS 5.1** (powershell.exe 5.1.26100) | 86 pass, **5 fail** | **97 pass, 0 fail** |

### Live A/B integration tests — 8 scenarios, real API calls

| # | Scenario | pwsh 7.5.4 | PS 5.1.26100 | Match? |
|---|----------|------------|--------------|--------|
| 1 | Get — VM basic (eastus) | ✅ PASS — 6 items | ✅ PASS — 6 items | Identical |
| 2 | Get — VM multi-region | ✅ PASS — 12 items | ✅ PASS — 12 items | Identical |
| 3 | Get — SQL Database vCore | ✅ PASS — 13 items | ✅ PASS — 13 items | Identical |
| 4 | Get — Storage Hot LRS | ✅ PASS — 8 items | ✅ PASS — 8 items | Identical |
| 5 | Get — App Gateway WAF v2 | ✅ PASS — 3 items | ✅ PASS — 3 items | Identical |
| 6 | Explore — VM Json (Top 5) | ✅ PASS — 5 items | ✅ PASS — 5 items | Identical |
| 7 | Explore — Redis search | ✅ PASS — 5 items | ✅ PASS — 5 items | Identical |
| 8 | Explore — App Gateway Table | ✅ PASS — 5 rows | ✅ PASS — 5 rows | Identical |

**16/16 PASS** — identical results across both runtimes for all scenarios.

## Out of scope (tracked in #413)

- `-File` mode array parameter collapse on PS 5.1 (docs update)
- `contains()` OData case-sensitivity (code fix with `tolower()`)

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed deduplication logic preventing array-type issues in Azure pricing calculations.
  * Improved error handling for HTTP failures to emit appropriate warnings instead of terminating unexpectedly.

* **Documentation**
  * Removed duplicate content in convention documentation.

* **Tests**
  * Enhanced test coverage for error handling scenarios across pricing operations.
  * Updated test compatibility requirements.

### CODE REVIEW

**Comment by ahmadabdalla** [comment]
## Review response

**Comments 1, 2, 3 — addressed in 9398014**

- **Pester detection** (comment 1): Tightened to check for exact 5.7.1 instead of any 5+. Prevents import failure when a different Pester 5.x is pre-installed — good catch, this was a latent bug exposed by lowering the version gate.
- **\\\ indentation** (comment 2): Aligned continuation line. Pre-existing but worth fixing while we're here.
- **ConvertFrom-JsonArray helper** (comment 3): Extracted helper with doccomment explaining the PS 5.1 unwrap rationale. 5 call sites now reference a single function.

**Comment 4 (StatusCode-only test) — respectfully declining**

The \\\ check uses \-or\ with both branches converging to identical behavior (warn + continue). There's no conditional logic downstream that differs based on *which* property exists. Our existing test validates the full error-handling path: exception detection → HTTP classification → warning output → loop continuation. A StatusCode-only variant would exercise the same code path with the same outcome. Test effort is better spent on scenarios with different outcomes (like the non-HTTP rethrow test we already have).

All 97 tests pass on both PS 7 and PS 5.1.
