### ISSUE TITLE
PS 5.1 compatibility regressions: test runner blocks 5.1, Explore-AzurePricing JSON broken, URI encoding diff

### ISSUE THREAD

**Issue by ahmadabdalla** [ahmadabdalla/azure-cost-calculator-skill#411]
## Problem

PR #395 (fixes #392) added PowerShell 5.1 compatibility to the pricing scripts. A/B testing on Windows (pwsh 7.5.4 vs PowerShell 5.1.26100) reveals **5 unit test failures on PS 5.1** and one real functional bug in the Explore script's JSON output.

## A/B Test Results

| Runtime | Passed | Failed | Total |
|---------|--------|--------|-------|
| **pwsh 7.5.4** | 87 | **0** | 87 |
| **PowerShell 5.1** | 82 | **5** | 87 |

### 1. Test runner blocks PS 5.1 entirely

`tests/unit/Run-PesterTests.ps1` has `#Requires -Version 7.0` on line 1. This hard-stops execution on PS 5.1 with:

`
The script 'Run-PesterTests.ps1' cannot be run because it contained a
"#requires" statement for Windows PowerShell 7.0.
`

The test runner should either drop the version gate or provide a PS 5.1-compatible path, since the scripts themselves now claim PS 5.1 support.

### 2. `Explore-AzurePricing.ps1` JSON output broken on PS 5.1 (4 failures)

**Root cause:** `ConvertFrom-Json` behaves differently between PS versions when parsing JSON arrays.

- **PS 7**: `ConvertFrom-Json` unwraps a JSON array into individual objects
- **PS 5.1**: `ConvertFrom-Json` returns the array as a **single nested object**

The script's JSON output path (` | ConvertTo-Json -Depth 3`) produces valid JSON on both runtimes, but when a consumer parses it with `ConvertFrom-Json` on PS 5.1, they get a single wrapper object containing an inner array instead of the expected flat list.

**Repro:**

`powershell
# PS 7 — works correctly
  = @('[{"a":1},{"a":2}]' | ConvertFrom-Json)
 .Count  # → 2

# PS 5.1 — broken
  = @('[{"a":1},{"a":2}]' | ConvertFrom-Json)
 .Count  # → 1  (wrapped array)
 [0].GetType()  # → System.Object[] (inner array)
`

**Failing tests:**

| Test | Expected | Got |
|------|----------|-----|
| Should return only distinct combinations | 2 | 1 |
| Should cap output to Top value | 3 | 1 |
| Should include ServiceName in each result | `'Virtual Machines'` | `@('Virtual Machines', 'Virtual Machines')` |
| Should include expected properties | `ServiceName, ProductName...` | `Count, Length, Rank, SyncRoot...` |

**This is a real functional bug** — not just a test issue. Any agent or downstream consumer parsing Explore output on PS 5.1 will get corrupted structure.

### 3. URI encoding difference for apostrophes (1 failure)

**Root cause:** `[System.Uri]::EscapeDataString()` behaves differently on .NET Framework 4.x (PS 5.1) vs .NET 8 (PS 7).

- **PS 7** (.NET 8): `'` → `%27` → `serviceName%20eq%20%27Virtual%20Machines%27`
- **PS 5.1** (.NET 4.x): `'` stays as `'` → `serviceName%20eq%20'Virtual%20Machines'`

The test asserts ` -like '*%27Virtual*Machines%27*'` which only matches the PS 7 encoding. The Azure Retail Prices API accepts both forms, so this is not a functional bug, but the test is PS 7-specific.

**Failing test:**

| Test | Issue |
|------|-------|
| should encode the filter parameter | Asserts `%27` encoding that only PS 7 produces |

### Fix 1: Remove `#Requires -Version 7.0` from test runner

Lower the gate to `#Requires -Version 5.1` or remove it entirely. Pester 5.7.1 works on PS 5.1 (confirmed during testing — installed and ran successfully).

### Fix 2: Fix `Explore-AzurePricing.ps1` JSON array output

Use a PS 5.1-safe wrapper so the output is consistently parseable. Options:

- **Option A**: Write `ConvertTo-Json -Depth 3` with explicit array wrapper that works on both runtimes
- **Option B**: Use `Write-Output` with `-NoEnumerate` or manually ensure array output

### Fix 3: Update URI encoding test assertion

Relax the test to accept both encoded (`%27`) and literal (`'`) apostrophes, since both are valid and the API accepts both.

### Fix 4: Add missing error-handling tests

PR #395 review comments flagged that the generic catch block could swallow non-HTTP exceptions. The current tests only cover the `[System.Net.WebException]` catch path. Add tests for:

- HTTP error on PS 7 (`HttpResponseException`)
- Non-HTTP exception rethrow (verify `throw` path works)
- Duck-type `-or` vs `-and` check correctness

## Files Affected

- `tests/unit/Run-PesterTests.ps1` — version gate
- `skills/azure-cost-calculator/scripts/Explore-AzurePricing.ps1` — JSON output
- `skills/azure-cost-calculator/scripts/lib/Invoke-RetailPricesQuery.ps1` — URI encoding
- `tests/unit/powershell/lib/Invoke-RetailPricesQuery.Tests.ps1` — encoding assertion
- `tests/unit/powershell/Explore-AzurePricing.Tests.ps1` — array parsing
- `tests/unit/powershell/Get-AzurePricing.Tests.ps1` — missing error tests

## Related

- #392 — Original PS 5.1 compatibility issue
- #395 — PR that introduced these changes
- #405 — Unit test coverage issue

**Comment by ahmadabdalla** [comment]
## Update: Live A/B Integration Test Results

Ran 8 live API test scenarios across both runtimes (pwsh 7.5.4 vs PowerShell 5.1.26100) using real service reference patterns (VMs, SQL Database, Storage, App Gateway, Explore).

### Side-by-Side Results

| # | Scenario | pwsh 7.5.4 | PS 5.1.26100 | Match? |
|---|----------|------------|--------------|--------|
| 1 | Get — VM basic (eastus) | **FAIL** — dedup bug | **FAIL** — dedup bug | Same bug |
| 2 | Get — VM multi-region | **FAIL** — dedup bug | **FAIL** — dedup + `-File` array collapse | PS 5.1 worse |
| 3 | Get — SQL Database vCore | **PASS** — $222.24 | **PASS** — $222.24 | Identical |
| 4 | Get — Storage Hot LRS | **PASS** — 3 tiered rows | **PASS** — 3 tiered rows | Identical |
| 5 | Get — App Gateway WAF v2 | **PASS** — $262.80 | **PASS** — $262.80 | Identical |
| 6 | Explore — VM Json (Top 5) | **PASS** — 5 items | **PASS** — 5 items | Identical |
| 7 | Explore — redis search | **WARN** — no results | **WARN** — no results | Identical |
| 8 | Explore — App Gateway Table | **PASS** — 5 items | **PASS** — 5 items | Identical |

### New Findings

#### NEW BUG: VM dedup logic breaks on both runtimes (pre-existing, not from #395)

The dedup code in `Get-AzurePricing.ps1` (~line 142) does:

`powershell
$primary = $group.Group | Where-Object { $_.isPrimaryMeterRegion -eq $true }
if ($primary) {
    $deduped.Add($primary)  # BUG: $primary can be an array
}
`

When multiple items share the same grouping key and all have `isPrimaryMeterRegion=true`, `$primary` is an **array**. This array gets added as a single element to `$deduped`, so later `$item.unitOfMeasure` is an array of strings, crashing `Get-MonthlyMultiplier`'s `[string]` parameter.

**Impact**: Breaks the most common query — Virtual Machines. Affects **both** PS 7 and PS 5.1.

**Fix**: `$deduped.Add(($primary | Select-Object -First 1))`

#### PS 5.1: `-File` mode collapses array parameters

`powershell.exe -File script.ps1 -Region 'eastus','australiaeast'` collapses the array into a single string on PS 5.1. This is a known `-File` mode limitation — it doesn't parse PowerShell expression syntax.

Multi-region queries silently fail with a 400 Bad Request. The SKILL.md rule 6 recommends `-File`, but agents targeting PS 5.1 need `-Command` for array arguments.

#### Explore JSON raw output is fine on both runtimes

The raw `[{...}, {...}]` JSON array is well-formed on both PS 7 and PS 5.1. The `ConvertFrom-Json` unwrapping issue from the original report only manifests when a **consumer** parses the output on PS 5.1 — the scripts themselves produce correct JSON. This narrows the scope of Fix 2 in the original issue: we may only need to adjust tests, not the script output.

#### `contains()` OData filter is case-sensitive

Both runtimes return zero results for `contains(productName, 'redis')` — the API uses "Redis" (capital R). Usability issue, not a PS version bug.

### Updated Issue Scope

| Finding | Affects | Severity | From PR #395? |
|---------|---------|----------|---------------|
| `#Requires -Version 7.0` in test runner | Test infra | Medium | No (from #405) |
| `ConvertFrom-Json` array unwrap (test-side) | Tests on PS 5.1 | Medium | Exposed by #395 |
| URI encoding `%27` vs `'` (test assertion) | Tests on PS 5.1 | Low | Exposed by #395 |
| **VM dedup `Add($primary)` bug** | **Both runtimes** | **Critical** | **No — pre-existing** |
| `-File` array param collapse on PS 5.1 | PS 5.1 multi-region | Medium | Compatibility gap |
| Missing error-handling tests | Test coverage | Medium | Gap from #395 |
| `contains()` case-sensitivity | Both runtimes | Low | Pre-existing |
